version: '3.8'
services:
  nginx:
    image: nginx:1.23.3-alpine
    container_name: 'nginx-app'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/hostPath/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '/hostPath/nginxLog:/var/log/nginx'
      - '/hostPath/letsEtc/live:/certs:ro'
      - '/hostPath/certbotAcmeChallenge:/data/www/acme-challenge:ro'
    networks:
      nginx-network:
        ipv4_address: 172.18.0.2
  certbot:
    image: certbot/certbot:v2.1.1
    container_name: 'nginx-certbot-app'
    volumes:
      - '/hostPath/letsEtc:/etc/letsencrypt'
      - '/hostPath/letsLib:/var/lib/letsencrypt'
      - '/hostPath/letsLog:/var/log/letsencrypt'
      - '/hostPath/certbotAcmeChallenge:/acme-challenge'
    networks:
      nginx-network:
        ipv4_address: 172.18.0.3
networks:
  nginx-network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/28
          gateway: 172.18.0.1
