version: '3.8'
services:
  nginx:
    image: 'nginx:1.23.3-alpine'
    container_name: nginx-app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/hostPath/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '/hostPath/nginxLog:/var/log/nginx'
      - '/hostPath/letsEtc/live:/certs:ro'
      - '/hostPath/certbotAcmeChallenge:/data/www/acme-challenge:ro'
    networks:
      rproxy-net:
        ipv4_address: 172.18.0.2
networks:
  rproxy-net:
    name: reverse-proxy-net
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/28'
          gateway: 172.18.0.1
