version: '3.9'

services:
  app:
    image: 'nginx:1.23.3-alpine'
    container_name: 'nginx-app'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '$(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro'
      - '$(pwd)/log_nginx:/var/log/nginx'
      - '$(pwd)/certs_live:/certs:ro'
    # - '$(pwd)/certbot_acme_challenge:/data/www/acme-challenge:ro'
    networks:
      - nginx-net
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'curl', '-fs', 'http://localhost' ]
      interval: 3m
      timeout: 30s
      retries: 3
      start_period: 30s

networks:
  nginx-net:
    name: 'nginx-net'
    ipam:
      driver: default
      config:
        - subnet: '172.18.0.0/28'
          gateway: 172.18.0.1
